name: "Create New Issue"
description: "Report a new issue"
title: "Issue: "
body:
  - type: markdown
    attributes:
      value: |
        Thank you for creating a new issue and contributing to our repository
  - type: textarea
    id: issue-description
    validations:
      required: true
    attributes:
      label: "💭 Description"
      description: "A clear and concise description of what the issue is."
  - type: checkboxes
    id: read-code-of-conduct
    attributes:
      label: "🏢 Have you read the Code of Conduct?"
      options:
        - label: "I have read the [Code of Conduct](https://github.com/anwilli5/coin-collection-android-US/blob/2d51333dd08c40c3fbc6a6897948209e1a6210c6/CODE_OF_CONDUCT.md)"
          required: true
